# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build Linux X86_64
        run: go build -o ./dist/server-linux-amd64

      - name: Build Windows X86_64
        run: GOOS=windows GOARCH=amd64 go build -o ./dist/server-windows-amd64.exe

      - name: Commit and push if changed
        run: |
          git config --global user.name "Bob the Builder"
          git config --global user.email "pernydev@gmail.com"
          git add .
          git commit -m "Build binaries"
          git push